/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Numan
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertStudentInfo = new javax.swing.JButton();
        addResult = new javax.swing.JButton();
        listStudent = new javax.swing.JButton();
        listStudentResult = new javax.swing.JButton();
        updateStudentMarks = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addadminButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 450));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertStudentInfo.setText("Insert Student Info");
        insertStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertStudentInfoActionPerformed(evt);
            }
        });
        getContentPane().add(insertStudentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, 31));

        addResult.setText("Add Result");
        addResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResultActionPerformed(evt);
            }
        });
        getContentPane().add(addResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 31));

        listStudent.setText("List Student");
        listStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentActionPerformed(evt);
            }
        });
        getContentPane().add(listStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 150, 31));

        listStudentResult.setText("List Student Result");
        listStudentResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentResultActionPerformed(evt);
            }
        });
        getContentPane().add(listStudentResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 150, 31));

        updateStudentMarks.setText("Update Student Marks");
        updateStudentMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentMarksActionPerformed(evt);
            }
        });
        getContentPane().add(updateStudentMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 150, 31));

        logOutButton.setText("LogOut");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, 50));

        deleteButton.setText("Delete Student Info");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 150, 30));

        addadminButton.setText("Add New Admin");
        addadminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addadminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addadminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Numan\\Documents\\NetBeansProjects\\StudentDatabaseManagementSystem\\Icons_ResultManagement\\schoolPic1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to close!!!", "Exit", JOptionPane.YES_NO_OPTION);
        if(response == 0){
            setVisible(false);
            Home frame = new Home();
            frame.setVisible(true);
        }
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void insertStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertStudentInfoActionPerformed
        // TODO add your handling code here:
        InsertStudent frame = new InsertStudent();
        frame.setVisible(true);
    }//GEN-LAST:event_insertStudentInfoActionPerformed

    private void updateStudentMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentMarksActionPerformed
        // TODO add your handling code here:
        UpdateResult frame = new UpdateResult();
        frame.setVisible(true);
    }//GEN-LAST:event_updateStudentMarksActionPerformed

    private void addResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResultActionPerformed
        // TODO add your handling code here:
        InsertResult frame = new InsertResult();
        frame.setVisible(true);
    }//GEN-LAST:event_addResultActionPerformed

    private void listStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentActionPerformed
        // TODO add your handling code here:
        ListStudent frame = new ListStudent();
        frame.setVisible(true);
    }//GEN-LAST:event_listStudentActionPerformed

    private void listStudentResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentResultActionPerformed
        // TODO add your handling code here:
        ListResult frame = new ListResult();
        frame.setVisible(true);
    }//GEN-LAST:event_listStudentResultActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DeleteStudentInfo frame = new DeleteStudentInfo();
        frame.setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addadminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addadminButtonActionPerformed
        // TODO add your handling code here:
        AddNewAdmin frame = new AddNewAdmin();
        frame.setVisible(true);
    }//GEN-LAST:event_addadminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResult;
    private javax.swing.JButton addadminButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton insertStudentInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listStudent;
    private javax.swing.JButton listStudentResult;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton updateStudentMarks;
    // End of variables declaration//GEN-END:variables
}
