/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectionProvider.ConnectionCode;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Numan
 */
public class InsertResult extends javax.swing.JFrame {

    /**
     * Creates new form InsertResult
     */
    public InsertResult() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rollnoTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insertButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        physicsMarksTextfield = new javax.swing.JTextField();
        mathsMarksTextfield = new javax.swing.JTextField();
        chemestryMarksTextfield = new javax.swing.JTextField();
        computerMarksTextfield = new javax.swing.JTextField();
        biologyMarksTextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 550));
        setMinimumSize(new java.awt.Dimension(550, 550));
        setPreferredSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Roll No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 24));

        rollnoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(rollnoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel2.setText("Physics Marks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, 20));

        jLabel3.setText("Maths Marks");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 20));

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(insertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 120, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 120, -1));

        jLabel4.setText("Chemestry Marks");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 20));

        jLabel5.setText("Computer Marks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 100, 20));

        jLabel6.setText("Biology Marks");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 100, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Roll No", "Gender", "Father's Name", "Course", "Branch"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 80));
        getContentPane().add(physicsMarksTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 174, 130, -1));
        getContentPane().add(mathsMarksTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 229, 130, -1));
        getContentPane().add(chemestryMarksTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 280, 130, -1));
        getContentPane().add(computerMarksTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 329, 130, -1));
        getContentPane().add(biologyMarksTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 382, 130, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Numan\\Documents\\NetBeansProjects\\StudentDatabaseManagementSystem\\Icons_ResultManagement\\schoolPic2.png")); // NOI18N
        jLabel7.setText("BackGround");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -20, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollnoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoTextFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        String rollNo = rollnoTextField.getText();
        int physicsMarks = Integer.parseInt(physicsMarksTextfield.getText());
        int mathsMarks = Integer.parseInt(mathsMarksTextfield.getText());
        int chemestryMarks = Integer.parseInt(chemestryMarksTextfield.getText());
        int computerMarks = Integer.parseInt(computerMarksTextfield.getText());
        int biologyMarks = Integer.parseInt(biologyMarksTextfield.getText());
        int total = physicsMarks+mathsMarks+chemestryMarks+computerMarks+biologyMarks;
        
        try{
            Connection con = ConnectionCode.getcon();
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO result VALUES('"+rollNo+"', "+physicsMarks+", "+mathsMarks+", "+chemestryMarks+", "+computerMarks+", "+biologyMarks+", "+total+")");
            JOptionPane.showMessageDialog(null, "Added Successfully!");
            setVisible(false);
            InsertResult frame = new InsertResult();
            frame.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String rollNo = rollnoTextField.getText();
        try{
            Connection con = ConnectionCode.getcon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = st.executeQuery("SELECT * FROM student WHERE rollNo = '"+rollNo+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first()){
                JOptionPane.showMessageDialog(null, "Entered RollNo doesn't exist!");
            }
            rollnoTextField.setEditable(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit!!!", "Exit", JOptionPane.YES_NO_OPTION);
        if(response == 0){
            setVisible(false);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biologyMarksTextfield;
    private javax.swing.JTextField chemestryMarksTextfield;
    private javax.swing.JTextField computerMarksTextfield;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mathsMarksTextfield;
    private javax.swing.JTextField physicsMarksTextfield;
    private javax.swing.JTextField rollnoTextField;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
